services:
  - type: web
    name: github-analyzer
    runtime: python
    rootDir: github_analyzer
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GITHUB_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
